when:
  event: manual
  branch: master

steps:
  backend:
    image: php:8.1
    commands:
      - apt-get update && apt-get install -y git unzip libzip-dev
      - docker-php-ext-install zip
      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
      - rm composer-setup.php
      - composer config --no-plugins allow-plugins true
      - composer install --no-dev --optimize-autoloader --ignore-platform-req=*
      - composer dump-env prod

depends_on:
  - setup