when:
  event: manual
  branch: master

steps:
  setup:
    image: alpine
    environment:
      ENV_VARS:
        from_secret: ENV_VARS
    commands:
      - echo "$ENV_VARS" > .env.prod
      - touch "build-$(date +%s)"

  front:
    image: node:14
    commands:
      - npm ci
      - npm run build

  backend:
    image: php:8.1
    depends_on:
      - setup
    commands:
      - apt-get update && apt-get install -y git unzip libzip-dev
      - docker-php-ext-install zip
      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
      - rm composer-setup.php
      - composer config --no-plugins allow-plugins true
      - composer install --no-dev --optimize-autoloader --ignore-platform-req=*
      - composer dump-env prod

  pack:
    image: alpine
    commands:
      - tar czf artifacts.tar.gz $CI_WORKSPACE
    artifacts:
      - artifacts.tar.gz