when:
  event: manual
  branch: master

skip_clone: true
depends_on:
  - build

matrix:
  SERVER:
    - azaw@172.26.214.158:/home/azaw/projects/deploy-target/
    - azaw@172.26.214.158:/home/azaw/projects/deploy-target-2/

steps:
  download:
    image: alpine
    commands:
      - apk add --no-cache scp
      - scp azaw@172.26.214.158:/home/azaw/projects/deploy-upload/_current.tar.gz .
      - tar xzf _current.tar.gz

  rsync:
    image: alpine
    depends_on:
      - download
    environment:
      SSH_PRIVATE_KEY:
        from_secret: SSH_PRIVATE_KEY
    commands:
      - apk add --no-cache openssh-client rsync
      - mkdir -p ~/.ssh
      - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - rsync -avz --exclude-from="$CI_WORKSPACE/.woodpecker/rsync-ignore" -e "ssh -i ~/.ssh/id_rsa" "$CI_WORKSPACE/" ${SERVER}
