when:
  event: manual
  branch: master

steps:
  setup:
    image: alpine
    depends_on: [ 'clone' ]
    environment:
      ENV_VARS:
        from_secret: ENV_VARS
    commands:
      - echo "$ENV_VARS" > .env.prod